### ISSUE TITLE
Duplicate records for Hydrokinetic Wave Energy Projects

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#16]
From User Surveys - There are 2 "Marine Hydrokinetic Projects for US Waters as of June 2014" datasets, one from data.gov, the other from MarineCadastre.gov. If the datasets are different, differentiate the layer names.

**Comment by tchaddad** [comment]
On the flip side, if the data sets are the same, then we want to only harvest it from the most direct, authoritative source. This is an easy (harvesting) fix.

**Comment by emiliom** [comment]
I fully agree with Tanya.

Also, this issue strikes me as being different from other WCODP issues. Unless @fishytodd is suggesting that the system could be modified to automatically detect duplicates (something that can be quite hard) and rename them, this issue is about the management of metadata records; not about actual portal functionality and capabilities. Maybe we need a label for "dataset" issues?
