### ISSUE TITLE
Categories check box bug

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#19]
From User Surveys - The category browsing is a little buggy. For example, when searching for wave energy, I'm presented with a category "Ecosystems And Functions", and a subcategory under that called "Species and Habitat Biodiversity". When I click the subcategory, both the category and subcategory are checked (this is fine). However, when I uncheck the category, I'd expect the subcategory to become unchecked as well...This does not occur. The buggiest part is when I uncheck the subcategory, the category becomes checked again. This definitely shouldn't happen.

**Comment by tchaddad** [comment]
Similar confusion in https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/14

**Comment by tchaddad** [comment]
I encountered something similar (using Firefox at least):
- new discover session: http://portal.westcoastoceans.org/discover/
- select a category with sub-categories, e.g. [Oceans](http://portal.westcoastoceans.org/discover/#?c=Category.Physical.Oceans) has 196 records
- now select a sub-category e.g. [Circulation](http://portal.westcoastoceans.org/discover/#?c=Category.Physical.Oceans.Circulation) The facet has 3 records listed

The user would expect to have now filtered down to 3 very relevant records, but that is not the case. Instead:
- Note that the Oceans facet now has 11 items and is for some reason unchecked
- Note that the checked Circulation facet lists 3 items (correct)
- Note that the list of results is showing the 11 items of the Ocean facet, even though Circulation facet is checked 

Further weirdness happens when the user tries to back out of where they are:
- uncheck Circulation facet
- note that Ocean becomes checked again with 196 records
- note that results list counts 552 records (wrong) 
- try changing number of records displayed on page to 50
- note that now number of records matches Ocean total of 196

Definitely buggy. This is probably a side effect of introducing the 2nd/3rd level hierarchy last year:
- one bug is that when third level facets are checked, results not filtered by the selected subcategory, and upper level facets do not maintain prior state as expected
- another bug is that when third level facets are subsequently unchecked, results lists do not correctly revert to pre-filter condition. 

There is probably more...

**Comment by jennywalsh** [comment]
Actual record numbers have changed since Tanya last commented.  However, the essential wonky-ness remains with the display of search records ignoring the sub-category facet selection by forcing in an "and" that necessarily contains the subcategory:

Use case
- start with a fresh Categories search
  - scroll to bottom and directly select Circulation (2) under Physical Data | Oceans 
  - Expected - 2 Circulation search results; only Circulation is selected; and the search summary reads " 2 results found for Oceans: Circulation"
  - Actual - Get 8 search results; the Oceans category is also selected (not what I intended); and the search summary at the top says "8 results found for Oceans: Circulation & Physical: Oceans".  

The 2 of circulation are included in the 8 total.

Unchecking Oceans, clears the check box and the term from the search summary but does not alter the total number of search results found.
