### ISSUE TITLE
Hyperlinks in Abstract/Constraints

### ISSUE THREAD

**Issue by cybersea** [WCGA/West-Coast-Ocean-Data-Portal#32]
If someone puts a URL in their Abstract or Constraints (for example), they do not show up as actual hyperlinks in the WCDOP.   

Is this something that is currently possible,  (i.e., by using HTML markup in the metadata)?  Or is it a capability that is of interest?   This inquiry was from Mara Dias at Surfrider.

See: http://wcga-vm01.sdsc.edu/discover/#?s=Sound%20GIS%20Test&text=surfrider

**Comment by tchaddad** [comment]
Requires parsing the entire Abstract field, and then applying link detection to the results. 

Better option is to wrap your abstract in CDATA tags, so that you can then insert HTML, for example:

`<gmd:abstract>
       <gco:CharacterString><![CDATA[ 
Since 1993, <b>Surfrider Foundation</b> Chapters have been collecting water quality data at beaches and in coastal watersheds through the volunteer-run, Blue Water Task Force program.  Water samples are processed using the IDEXX Quanti-Tray/2000 Method to test for enterococcus bacteria, a bacteria indicator used by the EPA to determine human health risk at beaches and in other recreational waters.  Surfrider lab and sampling site locations can be viewed at <a href="http://www.surfrider.org/blue-water-task-force">http://www.surfrider.org/blue-water-task-force</a> ]]>
        </gco:CharacterString>
</gmd:abstract>`

**Comment by tchaddad** [comment]
Closing in favor of prioritizing the other work on OPEN. Will link to those tickets as a reminder though...
