### ISSUE TITLE
Need to add ESRI REST link type for ISO-2 records

### ISSUE THREAD

**Issue by fishytodd** [WCGA/West-Coast-Ocean-Data-Portal#41]
Example record

http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={275A7879-7DEA-4D8D-8878-FCE04227835B}

**Comment by tchaddad** [comment]
Thanks Todd this should have been already covered by one of the scenarios we tested earlier, but I found an extra "." in the indexibles file that was preventing the case from being recognized.

I've placed a new version of apiso-2-indexables.xml in my /home/thaddad directory on dev. If you can copy it over to /usr/local/tomcat6/webapps/geoportal/WEB-INF/classes/gpt/metadata/iso and then reboot Tomcat so that Geoportal will recognize the change, it should take care of it.

**Comment by tchaddad** [comment]
The case in this situation was URL at the following path (in case Alison is watching):

gmi:MI_Metadata
gmd:distributionInfo
gmd:MD_Distribution
gmd:distributor
gmd:MD_Distributor
gmd:distributorTransferOptions
gmd:MD_DigitalTransferOptions
gmd:onLine
gmd:CI_OnlineResource
gmd:linkage
gmd:URL

**Comment by tchaddad** [comment]
I see there is also this apparently duplicate record on Dev:
http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={11FD2B65-AB49-4763-A0AC-CAE269E5BC0F}

I assume that this was an attempt to get the service directly from the server. If so, and if the above fix works, I believe this duplicate record should be removed from the collection.

**Comment by fishytodd** [comment]
Updated the file on dev, restarted tomcat, but still not seeing the ESRI
link showing up in the UI. It is coming through in geoportal. Is it a js
file edit that needs to happen as well?

http://wcga-vm01.sdsc.edu/discover/#?text=impaired

On Thu, Mar 19, 2015 at 7:07 PM, TC Haddad notifications@github.com wrote:

> I see there is also this apparently duplicate record on Dev:
> 
> http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={11FD2B65-AB49-4763-A0AC-CAE269E5BC0F}
> 
> I assume that this was an attempt to get the service directly from the
> server. If so, and if the above fix works, I believe this duplicate record
> should be removed from the collection.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/41#issuecomment-83852552
> .

## 

Todd R. Hallenbeck | Program Coordinator

West Coast Ocean Data Portal
West Coast Governors Alliance
Cell: (408) 482-6807
todd.r.hallenbeck@westcoastoceans.org
http://portal.westcoastoceans.org

**Comment by tchaddad** [comment]
I'll take a look - stay tuned. I'm fairly certain it is not a JS edit, so there may be a second reboot needed...

**Comment by tchaddad** [comment]
I'd like to ask @cybersea if there are any examples of other contributors showing ESRI REST in any ISO formats at all? The only record I can find in other GitHub issues (https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/21) is from ATSML.

ASTML seem to have switched to mostly FGDC records which are all working fine, but they seem to have 3 ISO records which are not showing their REST urls correctly:
- http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={34984053-4171-4AB8-AC06-94416249BF56}
- http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={738A0937-3552-4C13-BF70-63F2C3679971}
- http://wcga-vm01.sdsc.edu/geoportal/rest/document?id={A3299765-3FE0-4421-8FDD-D2ABE8D1E3C6}

**Comment by cybersea** [comment]
@tchaddad, There are no others that I know of.   Most of the ISO records are either from OR Coastal Atlas which all have OGC service formats or IOOS folks who don't generally have ESRI REST services either.   We could certainly create one for testing if you need it.

**Comment by tchaddad** [comment]
OK, I think we can declare that this issue was never solved for ASTML in #21, most likely because we had no representative test records (either ISO or ISO-2).  That makes this issue similar to what is being discussed in #23 for WMS and OpenDAP labels. 

I'm going to try to apply the partial fix from #23 (for WMS) to the problem in issue #41 (for ESRI REST). 

@fishytodd I still don't seem to have upload access to the Dev Server, so can you take the following files:
- /home/thaddad/20150326/apiso-indexables.xml
- /home/thaddad/20150326/apiso-2-indexables.xml
- /home/thaddad/20150326/gpt.properties

and move them respectively to:
- /usr/local/tomcat6/webapps/geoportal/WEB-INF/classes/gpt/metadata/iso/apiso-indexables.xml
- /usr/local/tomcat6/webapps/geoportal/WEB-INF/classes/gpt/metadata/iso/apiso-2-indexables.xml
- /usr/local/tomcat6/webapps/geoportal/WEB-INF/classes/gpt/resources/gpt.properties

and then reboot Tomcat so that Geoportal will recognize the change.

**Comment by fishytodd** [comment]
Moved the files, deleted files, reharvested, restarted geoportal...and it
worked!!! Looks like both the CA impaired waters records and the OSU
records now show the ESRI rest links. You can double check for yourself,
but I think we can call this one closed. Thanks Tanya!!!

We just need to replicate this on production. With your go aheead I can do
that, unless we anticipate further edits to those files.

On Thu, Mar 26, 2015 at 1:17 PM, TC Haddad notifications@github.com wrote:

> OK, I think we can declare that this issue was never solved for ASTML in
> #21 https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/21,
> most likely because we had no representative test records (either ISO or
> ISO-2). That makes this issue similar to what is being discussed in #23
> https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/23 for WMS
> and OpenDAP labels.
> 
> I'm going to try to apply the partial fix from #23
> https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/23 (for
> WMS) to the problem in issue #41
> https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/41 (for
> ESRI REST).
> 
> @fishytodd https://github.com/fishytodd I still don't seem to have
> upload access to the Dev Server, so can you take the following files:
> - /home/thaddad/20150326/apiso-indexables.xml
> - /home/thaddad/20150326/apiso-2-indexables.xml
> - /home/thaddad/20150326/gpt.properties
> 
> and move them respectively to:
> 
>    -
>    /usr/local/tomcat6/webapps/geoportal/WEB-INF/classes/gpt/metadata/iso/apiso-indexables.xml
>    -
>    /usr/local/tomcat6/webapps/geoportal/WEB-INF/classes/gpt/metadata/iso/apiso-2-indexables.xml
>    -
>    /usr/local/tomcat6/webapps/geoportal/WEB-INF/classes/gpt/resources/gpt.properties
> 
> and then reboot Tomcat so that Geoportal will recognize the change.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WCGA/West-Coast-Ocean-Data-Portal/issues/41#issuecomment-86697820
> .

## 

Todd R. Hallenbeck | Program Coordinator

West Coast Ocean Data Portal
West Coast Governors Alliance
Cell: (408) 482-6807
todd.r.hallenbeck@westcoastoceans.org
http://portal.westcoastoceans.org

**Comment by tchaddad** [comment]
That's great news. I think this means you can close both #21 and #41 once you have pushed to production. Woohoo!

**Comment by fishytodd** [comment]
Verified after push to production, closing issue.
